blank_issues_enabled: true
contact_links:
  - name: FAQ
    url: https://ibrowe.com/faq/
    about: Frequently Asked Questions
  - name: Help Center
    url: https://support.ibrowe.com/
    about: Help Center
  - name: Community
    url: https://community.ibrowe.com/
    about: Community support, this is the place to ask questions
