name: Assign issue labels
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
      with:
        enable-versioned-regex: 0
        include-title: 1
        configuration-path: .github/labeler.yml
        #sync-labels: 1 # This removes also manually added labels on edit
