name: Tweet nightly

on:
  issues:
    types:
      - labeled
      - closed

jobs:
  tweet-nightly:
    if: (github.event.action == 'labeled' && github.event.label.name == 'release-notes/social' && github.event.issue.state == 'closed') || (github.event.action == 'closed' &&  contains(github.event.issue.labels.*.name, 'release-notes/social'))
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: nearform-actions/github-action-notify-twitter@b3fa623c2f320117e8a08e20564c4ce0a5e67930 # v1.2.3
        with:
          message: "🎉 Issue resolved: ${{ github.event.issue.title }} by ${{ github.event.issue.user.login }}\n${{ github.event.issue.html_url }}"
          twitter-app-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
